version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: guillaudev/techtest
    docker:
      # specify the version
      - image: circleci/golang:1.13-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: yes
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $IMAGE_NAME:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $IMAGE_NAME:$TAG

workflows:
  version: 2.1
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
